name: Docker Build & Publish

description: Builds Docker Image and Pushes it to a Registry

inputs:
  IMAGE_NAME:
    description: Name of the image to be built
    required: false
    default: "latest"

  IMAGE_TAG:
    description: Tag of the image to be built
    required: false
    default: "ghcr.io/${{ github.repository }}"

  IMAGE_REGISTRY:
    description: Registry to push the image
    required: false
    default: ghcr.io

  DOCKER_USERNAME:
    description: Username to login to the registry
    required: false
    default: ${{ github.repository_owner }}

  DOCKER_PASSWORD:
    description: Password to login to the registry
    required: true

  DOCKERFILE_PATH:
    description: Path to the Dockerfile
    required: false
    default: Dockerfile

  PUBLISH:
    description: Publish the image to the registry
    required: false
    default: true

runs:
  using: composite

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker Image
      shell: bash
      run: docker build -f ${{ inputs.DOCKERFILE_PATH }} -t docker_image .

    - name: Login to Container Registry
      if: ${{ inputs.PUBLISH }}
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.IMAGE_REGISTRY }}
        username: ${{ inputs.DOCKER_USERNAME }}
        password: ${{ inputs.DOCKER_PASSWORD }}

    - name: Image Tagging
      if: ${{ inputs.PUBLISH }}
      shell: bash
      env:
        IMAGE_PATH: ${{ inputs.IMAGE_REGISTRY }}/${{ inputs.IMAGE_NAME }}
      run: |
        docker tag docker_image:latest ${IMAGE_PATH}:latest
        docker tag docker_image:latest ${IMAGE_PATH}:${{ inputs.IMAGE_TAG }}

    - name: Push Image to Registry
      if: ${{ inputs.PUBLISH }}
      shell: bash
      env:
        IMAGE_PATH: ${{ inputs.IMAGE_REGISTRY }}/${{ inputs.IMAGE_NAME }}
      run: |
        docker push ${IMAGE_PATH}:latest
        docker push ${IMAGE_PATH}:${{ inputs.IMAGE_TAG }}
