name: Clean Releases

description: Clean up Docker images and GitHub tags

inputs:
  CLEAN_IMAGES:
    description: Whether to clean Docker images
    type: boolean
    default: true

  CLEAN_TAGS:
    description: Whether to clean GitHub tags
    type: boolean
    default: true

  MIN_RELEASES:
    description: Minimum number of releases to keep
    type: integer
    default: 5
  
  REGISTRY:
    description: Registry to login
    required: false
    default: ghcr.io

  DOCKER_USERNAME:
    description: Username to login to the registry
    required: false
    default: ${{ github.repository_owner }}

  DOCKER_PASSWORD:
    description: Password to login to the registry
    required: true

runs:
  using: composite

  steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Registry
      if: ${{ inputs.CLEAN_IMAGES }}
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.REGISTRY }}
        username: ${{ inputs.DOCKER_USERNAME }}
        password: ${{ inputs.DOCKER_PASSWORD }}

    - name: Clean Docker Images
      if: ${{ inputs.CLEAN_IMAGES }}
      shell: bash
      run: |
        docker images | sort -nr
        # docker images | grep 'your_image_name:v*' | awk '{print $3}' | sort -nr | tail -n +${{ inputs.MIN_RELEASES }} | xargs docker rmi

    - name: Clean GitHub Tags
      if: ${{ inputs.CLEAN_TAGS }}
      shell: bash
      run: |
        git tag -l | sort -nr
        # | xargs git tag -d
        # git push origin --delete $(git tag -l --sort=-version:numeric | tail -n +${{ inputs.MIN_RELEASES }})
